import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 980 } });
await page.goto('http://localhost:3000/tmp-team-designs-check', { waitUntil: 'networkidle', timeout: 120000 });
const rail = page.locator('#portrait-rail');
await rail.scrollIntoViewIfNeeded();
await page.waitForTimeout(2000);
const scroller = rail.locator('div.overflow-x-auto').first();
const before = await scroller.evaluate((n) => n.scrollLeft);
const box = await scroller.boundingBox();
await page.mouse.move(box.x + box.width - 80, box.y + 40);
await page.mouse.down();
for (let i = 1; i <= 12; i += 1) await page.mouse.move(box.x + box.width - 80 - i * 25, box.y + 40);
await page.mouse.up();
await page.waitForTimeout(400);
const after = await scroller.evaluate((n) => n.scrollLeft);
const counter = await rail.locator('span.tabular-nums').first().innerText();
console.log({ before, after, dragged: after > before, counter });
await browser.close();
